export const ActionTypes={
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    FILTER_PRODUCT:"FILTER_PRODUCT",
    SELECTED_PRICERANGE_FILTER:"SELECTED_PRICERANGE_FILTER"
}